# Generated by Django 4.0.5 on 2022-06-26 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 6, 26, 21, 23, 51, 328582, tzinfo=utc)),
        ),
    ]
