# Generated by Django 4.0.5 on 2022-06-26 21:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 6, 26, 21, 28, 38, 462270, tzinfo=utc)),
        ),
    ]
