# Generated by Django 4.0.5 on 2022-06-26 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2022, 6, 26, 21, 29, 40, 365721, tzinfo=utc)),
        ),
    ]
