# Generated by Django 4.0.5 on 2022-06-27 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_slug_alter_task_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateField(default=datetime.date(2022, 6, 27)),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateField(default=datetime.date(2022, 6, 27)),
        ),
    ]
