# Generated by Django 4.0.5 on 2022-06-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_date_end_alter_task_date_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGGWPTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
