# Generated by Django 4.0.5 on 2022-06-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_delete_subggwptask_subtask_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='author',
        ),
    ]
